name: Generate Custom Snake Animation

on:
  schedule:
    - cron: '0 */12 * * *' # Runs twice a day to keep it fresh
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: ${{ github.repository_owner }}
          
          # These are the important customization lines
          outputs: |
            dist/github-snake.svg?color_snake=#0071e3&color_dots=#d2d2d7,#545458,#8dbdff,#0071e3
            dist/github-snake-dark.svg?palette=github-dark&color_snake=#0071e3&color_dots=#d2d2d7,#545458,#8dbdff,#0071e3
            dist/professional-snake.gif?font_size=18&color_snake=#0071e3&color_dots=#d2d2d7,#545458,#8dbdff,#0071e3&color_bg=#f5f5f7

      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
